### ISSUE TITLE
Setting DataTables options?

### ISSUE THREAD

**Issue by kriswema** [bgultekin/laravel-datatables-bundle#1]
Hej,
If I see it correctly, it's neither possible to pass aoColumnDefs nor general settings like pagination.
Is this something you have planned to implement? Am I supposed to do this some other way?

**Comment by bgultekin** [comment]
Hi,
Because columns can be specified at javascript/html-side, aoColumnDefs is not supported at this time. But, pagination is supported, also it is controlled at javascript-side with datatables settings (with iDisplayLength, iDisplayLength get data). Just create your query as you want and pass it to datatables-bundle, no more settings are required to handle pagination.
